# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_160', '0003_auto_20170709_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('user', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
