# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_160', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
